name: 'Deploy to Github Pages'

on:
  workflow_run:
    workflows: 
      - Lock Blogpost Metadata
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    
    steps:
      - uses: AshsWorkshop/actions/checkout@642654b8b40af8852255c1532e040378c42199aa # main

      - uses: AshsWorkshop/actions/setup-node@642654b8b40af8852255c1532e040378c42199aa # main
        with:
          node-version-file: '.node-version'

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Upload Build Artifact
        uses: AshsWorkshop/actions/upload-pages-artifact@642654b8b40af8852255c1532e040378c42199aa # main
  
  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: AshsWorkshop/actions/deploy-pages@642654b8b40af8852255c1532e040378c42199aa # main